services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro                                      #To have the same time as the host
      - /etc/localtime:/etc/timezone:ro                                       #To have the same time as the host
      - gluetun-volume-config:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD={OPENVPN_PASSWORD}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
    ports:
      - ${PORT_GLUETUN}:${PORT_GLUETUN}
      - ${PORT_GLUETUN}:${PORT_GLUETUN}/udp
      - "0.0.0.0:${PORT_QBITTORRENT}:${PORT_QBITTORRENT}"
      - "0.0.0.0:${PORT_QBITTORRENT}:${PORT_QBITTORRENT}/udp"
      - "0.0.0.0:${PORT_BAZARR}:${PORT_BAZARR}"
      - "0.0.0.0:${PORT_PROWLARR}:${PORT_PROWLARR}"
      - "0.0.0.0:${PORT_JELLYSEERR}:${PORT_JELLYSEERR}"
      - "0.0.0.0:${PORT_FLARESOLVERR}:${PORT_FLARESOLVERR}"
      - "0.0.0.0:${PORT_RADARR}:${PORT_RADARR}"
      - "0.0.0.0:${PORT_SONARR}:${PORT_SONARR}"
      - "0.0.0.0:${PORT_SPEEDTEST_TRACKER_VPN_HTTP_OUT}:${PORT_HTTP_DEFAULT}"
      - "0.0.0.0:${PORT_SPEEDTEST_TRACKER_VPN_HTTPS_OUT}:${PORT_HTTPS_DEFAULT}"
    networks:
      - docker-vpn-net

networks:
  docker-vpn-net:
    external: true

volumes:
  gluetun-volume-config:
    external: true