services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${PORT_QBITTORRENT}
      - TORRENTING_PORT=${PORT_GLUETUN}
    volumes:
      - /etc/localtime:/etc/localtime:ro                                      #To have the same time as the host
      - /etc/localtime:/etc/timezone:ro                                       #To have the same time as the host
      - qbittorrent-volume-config:/config
      - ${QBITTORRENT_DOWNLOADS_FOLDER}:/downloads
    network_mode: "container:gluetun"

volumes:
  qbittorrent-volume-config:
    external: true