services:
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro                                      #To have the same time as the host
      - /etc/localtime:/etc/timezone:ro                                       #To have the same time as the host
      - sonarr-volume-config:/config
      - ${QBITTORRENT_DOWNLOADS_FOLDER}:/downloads                              #qBittorrent downloads folder
      - ${TVSHOWS_FOLDER}:/data/tv-shows
      - ${ANIMATED_TVSHOWS_FOLDER}:/data/animated-tv-shows
      - ${TVSHOWS_FOLDER_1}:/data/tv-shows1
      - ${ANIMATED_TVSHOWS_FOLDER_1}:/data/animated-tv-shows1
      - ${TVSHOWS_FOLDER_2}:/data/tv-shows2
      - ${ANIMATED_TVSHOWS_FOLDER_2}:/data/animated-tv-shows2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    network_mode: "container:gluetun"

volumes:
  sonarr-volume-config:
    external: true
