services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro                                      #To have the same time as the host
      - /etc/localtime:/etc/timezone:ro                                       #To have the same time as the host
      - jellyseerr-volume-config:/app/config/
    network_mode: "container:gluetun"

volumes:
  jellyseerr-volume-config:
    external: true